Arithmetik:
	@./Kompilator -i "Beispiele/Arithmetik.deutsch" -o "Arithmetik.kompiliert" -b -d && \
	./Ausführer "Arithmetik.kompiliert"

Demonstration:
	@./Kompilator -i "Beispiele/Demonstration.deutsch" -o "Demonstration.kompiliert" -b -d && \
	./Ausführer "Demonstration.kompiliert"

Fakultät:
	@./Kompilator -i "Beispiele/Fakultät.deutsch" -o "Fakultät.kompiliert" -b -d && \
	./Ausführer "Fakultät.kompiliert"

LeeresProgramm:
	@./Kompilator -i "Beispiele/Leeres Programm.deutsch" -o "Leeres Programm.kompiliert" -b -d && \
	./Ausführer "Leeres Programm.kompiliert"

HalloWelt:
	@./Kompilator -i "Beispiele/Hallo Welt.deutsch" -o "Hallo Welt.kompiliert" -b -d && \
	./Ausführer "Hallo Welt.kompiliert"
