Arithmetik:
	@./Kompilator -i "Beispiele/Arithmetik.deutsch" -o "Arithmetik.kompiliert" -b -d && \
	./Ausführer "Arithmetik.kompiliert"

BedingteAnweisungen:
	@./Kompilator -i "Beispiele/Bedingte Anweisungen.deutsch" -o "Bedingte Anweisungen.kompiliert" -b -d && \
	./Ausführer "Bedingte Anweisungen.kompiliert"

Demonstration:
	@./Kompilator -i "Beispiele/Demonstration.deutsch" -o "Demonstration.kompiliert" -b -d && \
	./Ausführer "Demonstration.kompiliert"

Fakultät:
	@./Kompilator -i "Beispiele/Fakultät.deutsch" -o "Fakultät.kompiliert" -b -d && \
	./Ausführer "Fakultät.kompiliert"

Kommentare:
	@./Kompilator -i "Beispiele/Kommentare.deutsch" -o "Kommentare.kompiliert" -b -d && \
	./Ausführer "Kommentare.kompiliert"

LeeresProgramm:
	@./Kompilator -i "Beispiele/Leeres Programm.deutsch" -o "Leeres Programm.kompiliert" -b -d && \
	./Ausführer "Leeres Programm.kompiliert"

HalloWelt:
	@./Kompilator -i "Beispiele/Hallo Welt.deutsch" -o "Hallo Welt.kompiliert" -b -d && \
	./Ausführer "Hallo Welt.kompiliert"

Wiederholungen:
	@./Kompilator -i "Beispiele/Wiederholungen.deutsch" -o "Wiederholungen.kompiliert" -b -d && \
	./Ausführer "Wiederholungen.kompiliert"
